rcpx:
    resource: "@RCPXBundle/Resources/config/routing.yml"
    prefix:   /

votolab:
    resource: "@VotolabBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
  resource: "@UserBundle/Resources/config/routing.yml"